deploy:
  docker:
    - image: python:3.8

  steps:
    - checkout

    - run:
        name: Debug Snowflake Connection
        command: |
          set -x
          echo "export SNOWSQL_ACCOUNT=https://eu85787.us-east-2.aws.snowflakecomputing.com" >> $BASH_ENV
          echo "export SNOWSQL_USER=DEEPAKCYADAV822" >> $BASH_ENV
          echo "export SNOWSQL_PASSWORD=<Deepu@822>" >> $BASH_ENV
          source $BASH_ENV
          set +x

    - run:
        name: Check Environment Variables
        command: |
          echo "SNOWSQL_ACCOUNT: $SNOWSQL_ACCOUNT"
          echo "SNOWSQL_USER: $SNOWSQL_USER"
          echo "SNOWSQL_PASSWORD: $SNOWSQL_PASSWORD"

    - run:
        name: Install dbt
        command: |
          pip install dbt

    - run:
        name: Run dbt
        command: |
          dbt run


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
